name: EconomyAPI
version: 1.0.0
main: mc.fuckoka.economyapi.EconomyAPI
description: 経済プラグイン
author: deceitya
website: https://github.com/FuckokaMC/EconomyAPI
api-version: 1.21.4
load: POSTWORLD
depend:
  - DBConnector
libraries:
  - com.zaxxer:HikariCP:6.2.1
  - com.mysql:mysql-connector-j:9.1.0
permissions:
  economyapi.commands.money.show:
    default: true
  economyapi.commands.money.show.other:
    default: op
  economyapi.commands.money.pay:
    default: op
  economyapi.commands.money.set:
    default: op
  economyapi.commands.money.give:
    default: op
  economyapi.commands.money.take:
    default: op
  economyapi.commands.money.log:
    default: true
  economyapi.commands.money.log.other:
    default: op
  economyapi.commands.money.help:
    default: true
commands:
  money:
    description: お金コマンド
    permission: economyapi.commands.money.show
    usage: /money help
