name: EconomyAPI
version: 0.1.0
main: mc.fuckoka.economyapi.EconomyAPI
description: 経済プラグイン
author: deceitya
website: https://github.com/FuckokaMC/EconomyAPI
api-version: 1.21
load: POSTWORLD
depend:
  - CommandFramework
  - DBConnector
  - Vault
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.1.10
permissions:
  economyapi.commands.money.show:
    default: true
  economyapi.commands.money.show.other:
    default: op
  economyapi.commands.money.pay:
    default: op
  economyapi.commands.money.give:
    default: op
  economyapi.commands.money.take:
    default: op
  economyapi.commands.money.log:
    default: true
  economyapi.commands.money.log.other:
    default: op
  economyapi.commands.money.help:
    default: true
  economyapi.commands.money.validate:
    default: op
commands:
  money:
    description: お金コマンド
    permission: economyapi.commands.money.show
    usage: /money help
