CREATE TABLE wallets (
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    owner BINARY(16) NOT NULL UNIQUE,
    money INTEGER UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE money_transactions (
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    player INTEGER UNSIGNED,
    payee INTEGER UNSIGNED,
    amount INTEGER UNSIGNED NOT NULL,
    reason VARCHAR(255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (player) REFERENCES wallets(id),
    FOREIGN KEY (payee) REFERENCES wallets(id)
);
